export STARDLLS_VERSION=1.3.0
export PROTOCOL_VERSION=1.2.1
export STARLANG_VERSION=1.1.0
export DIPC_VERSION=1.5.0
export STARCORE_VERSION=1.3.8
export DPDK_VERSION=16.11.0
export STARFACE_VERSION=1.2.0
export STARFACE_NAME=tunpeer
export STARONOS_VERSION=1.8.2
export STAROS_VERSION=1.0.0
export STAROSCONTROLLER_VERSION=1.0.0
export STARFACESERVER_VERSION=1.2.2

